### PR TITLE
Rhino Transcoder upstream awareness

### PR DESCRIPTION
**Pull request by mrkno**
I'll start with this: **I don't actually expect this PR to be merged.** The changes are quite unstable and still need lots of work.

To make the Unicorn transcoder meet my quite specific use-case (auto-setup, auto-scaling) I've been making some quite large changes to its internals. I thought that you could benefit from awareness of the changes I'm making, hence this PR, and if desired you may wish to cherry pick some of them over to this awesome project.

Some key changes:
- redis has been replaced with a simple object inside the Load Balancer. Longer term I'll re-introduce a DB but for now this was to force API use between transcoder node and LB
- The transcoder automatically registers/deregisters itself with the Load Balancer using websockets
- As many as possible API routes are no longer proxyed direct to plex. Instead these are mirrored inside nginx because this is a more efficient and fast approach (see my Load Balancer Fork)
- Config as non-repo-committed `.json` file
- Widespread changes to make code async

### CODE REVIEW

**Comment by Maxou44** [comment]
This PR have a lot of new bugs, if everything was forwarded to Plex, it's not useless ;)

**Comment by drouarb** [comment]
Hey,
If you think it's unstable, I'm not sure we can merge it right now, I will review the changes soon. I think we could introduce the new changes into a branch and maybe merge them slowly into the main project.

**Comment by mrkno** [comment]
Yeah, as I said at the beginning this is more of an "FYI" PR than something I ever expect to get merged. Some of the changes might be useful, some of them might not. In particular the async and auto-registration stuff might be applicable to your more general use case.

The other changes I've made so far:
- https://github.com/UnicornTranscoder/UnicornTranscoder/compare/dev...mrkno:dev
- https://github.com/UnicornTranscoder/UnicornFFMPEG/compare/master...mrkno:master

**Comment by drouarb** [comment]
Actually this UnicornTranscoder is the second version of the project, I already rewriten it from scratch once. I think a full rewrite is necessary and a lot of things could be improved

**Comment by drouarb** [comment]
I seen that you replaced the redis by websockets, even if redis is not the good solution for this project, I think that websockets are not a good solution as well until a similar specification is available in http2.

**Comment by drouarb** [comment]
We just released the 2.0, most of what you wanted is inside this new version, you should have a look

**Pull request closed without merging**
